spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ketangpai?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: 12xuhua12.
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
